version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
install:
- cmd: >-
    git clone https://github.com/microsoft/vcpkg

    cd vcpkg

    call bootstrap-vcpkg.bat

    vcpkg.exe integrate install

    vcpkg.exe install boost-asio:x64-windows nlohmann-json:x64-windows spdlog:x64-windows

    cd ..
clone_script:
- cmd: git clone --recursive https://github.com/SleepingSoul/Remote-Gamepad
build:
  project: Remote-Gamepad/RemoteGamepad/RemoteGamepad.sln
  parallel: true
  verbosity: normal